# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Run Swift Lint"
  lane :swift_lint do
    swiftlint
  end
  
    desc "Run Unit Test Cases"
  lane :run_unit_test_cases do
    run_tests()
  end
  
end
